[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[terminal.shell]
program = "/bin/bash"
args = ["-l", "-c", "~/.tmux/sessions.sh"]
